development:
  adapter: postgresql
  host: localhost
  database: storyward_development

test:
  adapter: postgresql
  host: localhost
  database: storyward_test

production:
  adapter: postgresql
  host: localhost
  database: storyward_production
